version: "3.9"

services:
  api:
    image: 173763384281.dkr.ecr.us-east-1.amazonaws.com/chatbot-api:latest
    container_name: chatbot-api
    ports:
      - "8000:8000"
    environment:
      OPENSEARCH_COLLECTION_ENDPOINT: ${OPENSEARCH_COLLECTION_ENDPOINT}
      Access_Key: ${Access_Key}
      Secret_Access_Key: ${Secret_Access_Key}
      AUTH_SECRET_KEY: ${AUTH_SECRET_KEY}
    restart: unless-stopped
